### ISSUE TITLE
[Analytics] Click rate of tags in article page

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2552]
### Tasks
- [ ] need a board for tag analysis
- [ ] click rates of
  - [ ] both users and visitors
  - [ ] both desktop and mobile device
- [ ] numbers of user and visitors actually scroll to see more tags

### References
- [notion](https://www.notion.so/matterslab/13624071aec641c2b46cf4a7343a697f)
