### ISSUE TITLE
Home page feed tabs refactor

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2583]
### Tasks
- [ ] Feed tab redesign
- [ ] Create component for scrolling feed tab and management
- [ ] Local setup for visitor

### Design
- [figma](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=3696%3A22867)

**Comment by devformatters** [comment]
@ElkLeung please add draft PR. 🙏🏻

**Comment by devformatters** [comment]
Issue requires review and rearrangement. Close it.
