### ISSUE TITLE
Setup testing framework

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2657]
### Tasks
- [x] Remove current testing framework: Cucumber, Nightwatch, Jest, etc.;
- [x] Setup testing framework;
- [x] Integrate to CI/CD;
- [x] Write basic test cases (provided by @devformatters);

### Scope
* [matters-web](https://github.com/thematters/matters-web)

**Comment by devformatters** [comment]
@Jasmine-liang 
Making smaller PRs is better for changes review.

**Comment by Jasmine-liang** [comment]
CI integration ref: [Adding Playwright tests into the GitHub pipeline](https://kontent.ai/blog/next-js-playwright-tests-github-action/)
