### ISSUE TITLE
[Web] Toast & update translation button

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2659]
### Tasks
- [ ] Toast message
  - [ ] only show once
  - [ ] automatically dismiss after 5 seconds
  - [ ] click and then dismiss
- [ ] Update sharing dialog

### References
- [Product doc](https://paper.dropbox.com/doc/Matters--BnPlPH6Hax1Xofp87fvvAW3IAg-CIYsKQj8cmr4STCXWQIxA)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=6092%3A35924)

**Comment by guoliu** [comment]
Still needs discussion on whether we should use subdomain (e.g. `en.matters.news/...`) or subpath (e.g. `matters.news/en/...`)
