### ISSUE TITLE
Setup translation library

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2755]
### Tasks
- [x] Confirm & setup format.js;
- [ ] Integrate to CI/CD pipeline and development workflow;
- [ ] Make reusable util or component if needed;
- [x] Sample translations; 

### References
* https://www.notion.so/matterslab/i18n-Translations-6bd5b64ea85d4b8595a7ca20a43cab6e

**Comment by devformatters** [comment]
@Jasmine-liang This is accomplished ?
