### ISSUE TITLE
Translate core UI texts and copies

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2757]
### Upstream Tasks
* https://github.com/thematters/matters-web/issues/2756

### Tasks
- [ ] Extract translations to (JSON) files;
- [ ] Hand over to colleagues for translation [0];
- [ ] Compile and commit back to codebase;

### Refs
[0] https://crowdin.com
[1] https://github.com/formatjs/formatjs/blob/main/crowdin.yml

**Comment by devformatters** [comment]
@Jasmine-liang This is accomplished ?

**Comment by Jasmine-liang** [comment]
Yes
