### ISSUE TITLE
Correct English copies

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2784]
### Tasks
- [x] Correct `Follow` to `Following`

<img width="55%" src="https://user-images.githubusercontent.com/34237112/190944138-24b3b8d7-734f-4660-bed3-1730d905c89d.png">

- [x] Change `Notification` to `Notifications`
<img width="55%" src="https://user-images.githubusercontent.com/34237112/190944245-f1f4c03c-e807-4708-ac5a-8a60ae865d24.png">

- [x] Fix Super Like copies
- [x] Change `register` to `Register`
<img width="55%" src="https://user-images.githubusercontent.com/34237112/190944348-d782ac56-2986-4fce-a2af-744c0997f888.png">

- [x] Circle notice settings
<img width="55%" src="https://user-images.githubusercontent.com/34237112/191278364-5e1dae97-53d9-4fd5-8c85-f09c77fc69f2.png">

**Comment by Jasmine-liang** [comment]
Manage Circle Profile needs copies fix also

![Image](https://user-images.githubusercontent.com/63624438/191780854-3b014e54-c5af-4ff5-ad3d-2c3a00ebea41.png)
