### ISSUE TITLE
[Web] Add testing cases (comments & notices)

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2788]
### Tasks
- [ ] Add testing cases for article commenting
- [ ] Add testing cases for article commenting notice
- [ ] Add testing cases for article publishing notice

**Comment by devformatters** [comment]
3

**Comment by Jasmine-liang** [comment]
- [Cache the Playwright Browser Binaries](https://playwrightsolutions.com/playwright-github-action-to-cache-the-browser-binaries/)

**Comment by robertu7** [comment]
need to reorg, will open other issues and cover test cases of this issue's.
