### ISSUE TITLE
Implementation of support feedback

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2810]
### Tasks
- [ ] Update support flow last step
- [ ] Add animation into article page
- [ ] Update support section

### References
- [Product doc](https://paper.dropbox.com/doc/Matters--BqdxffYuRPBH7Ql~Sg7Z8ssWAg-3lhxiAzEnwkCA6SaphWXY)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=6562%3A41913)

**Comment by devformatters** [comment]
3
