### ISSUE TITLE
Update content in /guide

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2822]
### Tasks
- [x] Revise main guide content
- [ ] Replace PWA installation tutorial with new one, include footer
- [x] Replace wallet connection tutorial with new one
- [x] Add wallet login tutorial with new one
- [ ] Fix payment tutorial article link

### References
- [slack](https://mattersnews.slack.com/archives/G9CAFND7D/p1665478353876059)
- [copies](https://docs.google.com/document/d/1_bT8bbh1DOVkJgerYbnB7m7l2uOLzPVuUM_zCkBRs8k/edit)
