### ISSUE TITLE
Add help information in support UI

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2830]
### Tasks
- [ ] Add guide link in support method selection view
- [ ] Add pop-up in support amount setup view
- [ ] Add help info in support amount setup view

###
- [Design #1](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI?node-id=4632:26983#286917116)
- [Design #2](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=8449%3A47975)
