### ISSUE TITLE
UI of support currency conversion

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2856]
### Tasks
- [ ] ~add conversion options~
- [ ] display converted results in support UIs:
  - [ ] payment method selection
  - [ ] amount setup

### References
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=4632%3A24917)

### Blocked By
- https://github.com/thematters/developer-resource/issues/164
