### ISSUE TITLE
UI of received rewards in dashboard

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2869]
### Tasks
- [ ] create UI of `received rewards` in dashboard
- [ ] add a interactive chart in received reward block
- [ ] show placeholder to encourage user to write if no article published

### References
- [Product doc](https://paper.dropbox.com/doc/Matters--BsFuKLWrYK6OJLz9wmLqO7L8Ag-FY6LniQcV9npvLvAfZ6S0)
- [Design]()

**Comment by devformatters** [comment]
Issue requires review and rearrangement. Close it.
