### ISSUE TITLE
Handle article ipfs hash null

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2882]
### Tasks
- [ ] Adjust `<FingerprintDialog>` and show ISCN-like pending UI;
- [ ] Adjust `toPath` (used by `<Head>`) to support handing null value of `mediaHash`;
- [ ] Confirm if queries/mutations that using `mediaHash` are working correctly;

**Comment by robertu7** [comment]
![Image](https://user-images.githubusercontent.com/4065233/199397852-f31d9210-4ca2-4854-87d8-5cae7e53b344.png)

Also change the url from `https://matters.news/@{username}/{articleId}-{slug}-{mediaHash}` to `https://matters.news/@{username}/{articleId}`
