### ISSUE TITLE
Revise search details page

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2953]
### Blockers
- https://github.com/thematters/matters-web/issues/2950

### Tasks
- [ ] Subpages: Articles, Users & Tags;
- [ ] No search result page;
- [ ] Long text input
- [ ] Show Search Button in mobile keyboard,

### References
- [Product doc](https://www.notion.so/matterslab/Search-Rework-c66bd1db9c9c49d8a5a4b22cff5244b7)
- [Design](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=9980%3A59691&t=bnYjlt6sIqpl6HOF-4)

**Comment by pitb2022** [comment]
Long text input

**Comment by pitb2022** [comment]
add Task: show Search Button in mobile keyboard, design note ref: https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=9584%3A54865&t=QO34UcUQdhNR9uQw-4

**Comment by pitb2022** [comment]
New requirement: keyboard op ref: https://www.notion.so/matterslab/Search-Rework-c66bd1db9c9c49d8a5a4b22cff5244b7#10d1aa934535487d963c7a71f4072f50
