### ISSUE TITLE
Test case: homepage

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#2957]
### Tasks
- [ ] **Test**: homepage rendering
- [ ] **Test**: infinite scroll
- [ ] **Test**: tab switching
- [ ] **Practices**: locators & selectors

### References
* https://playwright.dev/docs/locators
* https://playwright.dev/docs/selectors
