### ISSUE TITLE
Make counts to one decimal place

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#2998]
### Tasks

- Make counts to one decimal place. Affected components are: 

  - [x] Home page tag card top counts
  - [x] All tag page tag card footer counts
  - [x] User profile followers and article counts
  - [x] Circle page member and followers counts
  - [x] Circle card footer counts

### References

- [Thread discussion](https://mattersnews.slack.com/archives/G8EGL8FU2/p1671052848821449?thread_ts=1669061368.606889&cid=G8EGL8FU2)

**Comment by Jasmine-liang** [comment]
- [ ] Followers and Following counts.
