### ISSUE TITLE
Move Next.js assets to R2

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3006]
### Tasks
- [x] Upload assets to R2 (`.github/workflows/deploy.yml`)
- [x] Create a R2 bucket and a new domain
- [x] Change `NEXT_PUBLIC_NEXT_ASSET_DOMAIN` to the new domain
- [x] Add domain to CSP (if needed)
- [ ] Update configuration of CORS (if needed)

**Comment by robertu7** [comment]
Configure CORS on R2: https://kian.org.uk/configuring-cors-on-cloudflare-r2/

**Comment by robertu7** [comment]
Ran below command and works:

```bash
aws s3api put-bucket-cors --bucket matters-assets-next-develop --cors-configuration '{"CORSRules" : [{"AllowedHeaders":["Authorization"],"AllowedMethods":["GET","HEAD","POST"],"AllowedOrigins":["*"],"ExposeHeaders":["Access-Control-Allow-Origin"]}]}' --endpoint-url https://757aaed316df635d8deb63859258808c.r2.cloudflarestorage.com
```
