### ISSUE TITLE
Quick search UI / UX fixes

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3011]
### Tasks
- [x] Mobile 取消 quick result
- [x] 无需 loading 提示
- [x] 结果无法右键新 tab 打开
  - 請確認標籤與用戶是否都正常
- [x] 点击结果条目后下拉结果应消失
- [x] 全结果页面不应再激活 quick result
- [x] 键盘快捷操作没有选中提示
  - 悬停高亮显然太浅，显示默认黑框即可

### References

- [Thread discussion](https://mattersnews.slack.com/archives/G8877EQMS/p1672133771368389)
