### ISSUE TITLE
Translation migration Pt.1

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3186]
### Tasks
Migrate copies in below pages including in clickable components:

- [x] Notice page
- [x] Login & Register modal (both email and wallet)
- [x] Login & Register page
- [ ] Navigation
- [ ] Global page footer & Language switch
- [ ] Home page
  - [ ] Feeds article cards
  - [ ] Topics feed cards
  - [ ] Authors feed cards
  - [ ] Search input
  - [ ] Wallet connect button

**Comment by devformatters** [comment]
@Jasmine-liang
Please prepare a disposable account that receive all kinds of notices for others to review
