### ISSUE TITLE
Translation migration Pt.2

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3187]
### Tasks
Migrate copies in below pages including in clickable components:

- [x] User page
  - [x] Share user modal
  - [x] `...`  Dropdown menu
  - [x] Content feed modal
  - [x] Circle component
  - [x] Feeds
- [x] User analytics page
- [ ] Tag page
  - [ ] `...`  Dropdown menu
  - [ ] Feeds
  - [ ] Related tags
- [ ] Circle page
  - [ ] `...`  Dropdown menu
  - [ ] Feeds
  - [ ] Circle Subscription
