### ISSUE TITLE
Following page renew

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3226]
### Tasks
- [ ] Remove xxx published
- [ ] Move circle and tag to the card footer
- [ ] Replace `xxx 廣播於 xxx_circle：` with `xxx_circle new 新廣播：` 
- [ ] Remove unfollow button

### References
- [Design v3](https://www.figma.com/file/oGew0i2s0N8IBm9tCpoLLI/%E8%BF%AD%E4%BB%A3%E8%A8%AD%E8%A8%88%E4%B8%AD%E7%B9%BC%E7%AB%99?node-id=1013%3A839&t=hgXvBf5Z7B99gSBN-1)

**Comment by devformatters** [comment]
@pitb2022 I added a new tasks `circle broadcast` and design. Please check. 🙏🏻
