### ISSUE TITLE
Renew adding article connection workflow

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3262]
### Tasks
- [ ] Create a new component with some reusable parts:

  - [ ] New search and select UX design
  - [ ] Add deletion confirm step
  - [ ] Set the max number of connections to 10

### References
- [Design](https://www.figma.com/file/vO8f8jaz9cZo1DsAazvHWd/Matters.news-%E8%BF%AD%E4%BB%A3%E8%AE%BE%E8%AE%A1?node-id=0%3A1&t=QR4gWQuujcHbEIbU-0)

### Blockers
- https://github.com/thematters/matters-server/issues/3222
