### ISSUE TITLE
Few UI changes & fixes

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3294]
### Tasks
- [ ] Remove hover style from list component
- [ ] Renew expandable design
- [ ] Fix circle expandable in following page
- [ ] Fix font sizes in article card footer
- [ ] Fix support font size
- [ ] Remove payout notice codes

### References
- [Thread](https://mattersnews.slack.com/archives/G8877EQMS/p1678807769434209)
- [Thread](https://mattersnews.slack.com/archives/GA0R09FHN/p1679282974278069?thread_ts=1679061496.488239&cid=GA0R09FHN)
- [Report](https://matters.canny.io/bug-reports/p/d08994)
