### ISSUE TITLE
Update form validations to restrict new user name in lower case

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3299]
### Tasks
- [ ] Update form validations in pages:
  - [ ] Registration
  - [x] Change user name
- [x] Change input hints
- [x] Change error message
- [x] Add E2E test cases

### References
- [Thread](https://mattersnews.slack.com/archives/G805NQVE3/p1678159872394439) 

### Blockers
- https://github.com/thematters/matters-server/issues/3244

**Comment by robertu7** [comment]
Due to changing username needs email verification, we can't make a full E2E test, we only test [input normalization](https://github.com/thematters/matters-web/pull/3318/files#diff-f3c7f9f82f6dcd4222936d31ebc8e729cab2153be5fef6bc1b5c22e181403de7) here.

@devformatters @pitb2022
