### ISSUE TITLE
Some UI changes

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-web#3403]
### Tasks
- [ ] Update draft list page
- [ ] Circle card hover style
- [ ] Change copies in user profile
- [ ] Editor scroll bar
- [ ] Update English copies of community page

### References
- [doc](https://paper.dropbox.com/doc/2023-04-Design-Feedback--B3OkArCbpxxDk7LTTAoa~M30Ag-kqsugQdC8IjAhjLOGQQRN)
- [copy of community page](https://docs.google.com/document/d/1va0fE9Di-P5lRJFZjrAk1-Vbc-yJtFukS2Hmyndl0y0/edit)
