### ISSUE TITLE
Referral tracking

### ISSUE THREAD

**Issue by robertu7** [thematters/matters-web#3956]
### Tasks
- [ ] Revise analytics/tracking components to support emit events via Matters API;
- [ ] referral tracking with localStorage or cookie;
- [ ] Emit referral events via Matters API;

### Stories
* https://github.com/thematters/developer-resource/issues/307
