### ISSUE TITLE
Articles Versioning

### ISSUE THREAD

**Issue by pitb2022** [thematters/matters-web#4176]
### Todos

 - [ ] Draft Editor Input
 - [ ] Header Area
 - [ ] Switch Area
   - [ ] Sidebar in Desktop
   - [ ] Dropdown menu in mobile
 - [ ] Content

---

### Story
- https://github.com/thematters/developer-resource/issues/321
