### ISSUE TITLE
Revise free write event avatar list

### ISSUE THREAD

**Issue by zeckli** [thematters/matters-web#4738]
### Todo
- [ ] revise free write event avatar list
- [ ] refactor drawer component if needed
- [ ] add drawer for `see full participants`

### References
- [design](https://www.figma.com/design/vDS1dPrYuM7EHTeIaA9cPs/%E8%87%AA%E7%94%B1%E5%AF%AB?node-id=3926-3811&t=cayPuJzRwsQiNI9D-1)
